### ISSUE TITLE
The reader object: IndexError: list index out of range for 2020-05-26 TOPS data and something else for DEEP

### ISSUE THREAD

**Issue by summacod** [rob-blackbourn/iex_parser#1]
with Parser(TOPS_SAMPLE_DATA_FILE, TOPS_1_6) as reader:
    for message in reader:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xxxx/anaconda3/envs/iexparser/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/xxxxx/anaconda3/envs/iexparser/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxxxx/anaconda3/envs/iexparser/lib/python3.8/site-packages/iex_parser/parser.py", line 68, in _fill
    packet: Packet = self.reader.read_packet()
  File "/home/xxxxxx/anaconda3/envs/iexparser/lib/python3.8/site-packages/scapy/utils.py", line 1207, in read_packet
    rp = super(PcapNgReader, self).read_packet(size=size)
  File "/home/xxxxxxx/anaconda3/envs/iexparser/lib/python3.8/site-packages/scapy/utils.py", line 1130, in read_packet
    res = self.blocktypes.get(blocktype,
  File "/home/xxxxxx/anaconda3/envs/iexparser/lib/python3.8/site-packages/scapy/utils.py", line 1164, in read_block_epb
    RawPcapNgReader.PacketMetadata(linktype=self.interfaces[intid][0],  # noqa: E501
IndexError: list index out of range

Stops right here,

quote_update,0,26.05.2020 13:36:13:287240,XLB,0,0,0,0
quote_update,0,26.05.2020 13:36:13:287495,GFI,100,7.76,0,0
quote_update,0,26.05.2020 13:36:13:287751,TNA,100,26.38,0,0
quote_update,0,26.05.2020 13:36:13:288048,XLK,100,97.97,0,0
quote_update,0,26.05.2020 13:36:13:288191,QQQ,100,232.42,100,232.62

**Comment by summacod** [comment]
Same with Deep data as well, 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xxxxx/anaconda3/envs/iexparser/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/xxxxxx/anaconda3/envs/iexparser/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxxxxx/anaconda3/envs/iexparser/lib/python3.8/site-packages/iex_parser/parser.py", line 79, in _fill
    layer: UDP = packet[UDP]
  File "/home/xxxxx/anaconda3/envs/iexparser/lib/python3.8/site-packages/scapy/packet.py", line 1171, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [UDP] not found


Stops right here,
price_level_update,S,1,26.05.2020 13:33:17:200339,HAL,100,11.98
price_level_update,S,1,26.05.2020 13:33:17:200649,XLV,0,100.55
price_level_update,B,1,26.05.2020 13:33:17:201109,QLD,100,131.25
price_level_update,S,1,26.05.2020 13:33:17:201116,QLD,100,131.35
price_level_update,B,1,26.05.2020 13:33:17:201126,UDOW,100,59.22

**Comment by rob-blackbourn** [comment]
Hi @summacod 

What versions of iex_parser and scapy do you have? (the command `pip freeze` should show this)

Also what OS and version?

Rob

**Comment by rob-blackbourn** [comment]
Hi @summacod 

I've found a potential bug, made a fix, and published as version "1.5.1".

However I read both files and got no errors, so I suspect there's something odd in your installation.

Can you give the new version a try and let me know how you get  on?

Rob

**Comment by summacod** [comment]
Sorry, i did not have time, i will try to test, meanwhile i moved to Java. I might also have had potential issue with my memory.
