### ISSUE TITLE
Key error 73 on recent data

### ISSUE THREAD

**Issue by DemenzEchtbaer** [rob-blackbourn/iex_parser#4]
Hi Rob, thanks for bringing us iex_parser!

I get a key error: 73 for the most recent data, although your package works wonders for older data (I haven't found the working/notworking"cutoff" yet but I probably will at some point). Could you suggest a workaround?

Thanks in advance.

**Comment by DemenzEchtbaer** [comment]
A few precisions:
- everything still worked fine up until 2020/12/31 but the key error 73 was already present on 2021/12/31 (I still havbe to check in between)
- the entire error message is as follows:  
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/parser.py", line 85, in _fill
    messages = self._read(buf)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/parser.py", line 116, in _read
    message = self._parse_message(buf[start:end])
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/parser.py", line 125, in _parse_message
    return decode_message(self.protocol, message_type, message_body)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/messages.py", line 336, in decode_message
    return _VERSIONED_DECODERS[version][message_type](buf)
KeyError: 73

**Comment by rob-blackbourn** [comment]
Hi,

It's been a while since I went to the website and it's all changed. I can't find the files to download so I can test.

Do you have a url where I can download a file?

Thanks,

Rob

**Comment by rob-blackbourn** [comment]
Cancel that, I've found them!

Let's see what's going on.

**Comment by DemenzEchtbaer** [comment]
Hehe, you were faster than me! Looking forward to what you may find ;-)

**Comment by rob-blackbourn** [comment]
Was it TOPS or DEEP?

**Comment by DemenzEchtbaer** [comment]
> Was it TOPS or DEEP?

Both, it seems.

**Comment by DemenzEchtbaer** [comment]
> Looks like there's at least one new message "Retail liquidity Indicator - I (0x49)"
> 
> I'll find out more when the (huge) file has downloaded.

Indeed, they have gotten heavier over time. Also, some of the older files exhibit strange trading hours, e.g. 2020/09/30: market opens at 14:30:00 UTC...and the last trade report comes in at 14:37:52! Did the csv parser stopped working midway, did IEX effectively close after 7 minutes, or did they upload uncomplete data...have you ever encountered this scenario before?

**Comment by rob-blackbourn** [comment]
I've made some fixes and published version "1.7.0" to pypi.

Can you let me know if it solves the issues?

**Comment by DemenzEchtbaer** [comment]
> I've made some fixes and published version "1.7.0" to pypi.
> 
> Can you let me know if it solves the issues?

So it was going fine for a while with 20220114 TOPS (using the command line csv parser), but it broke when it reached (821000):

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-01-14T14:31:33.002424+00:00 (821000)
    self.run()
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/parser.py", line 85, in _fill
    messages = self._read(buf)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/parser.py", line 104, in _read
    raise RuntimeError('Invalid payload')
RuntimeError: Invalid payload

EDIT: it seems the issue is not present for DEEP (currently parsing 2022-01-13)

**Comment by DemenzEchtbaer** [comment]
This is what I get for an older file (20211231 TOPS):
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/parser.py", line 85, in _fill
    messages = self._read(buf)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/parser.py", line 116, in _read
    message = self._parse_message(buf[start:end])
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/parser.py", line 125, in _parse_message
    return decode_message(self.protocol, message_type, message_body)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/messages.py", line 352, in decode_message
    return _VERSIONED_DECODERS[version][message_type](buf)
  File "/home/demenzechtbaer/anaconda3/lib/python3.8/site-packages/iex_parser/messages.py", line 126, in _decode_quote_update
    ) = struct.unpack('<Bq8sLqqL', buf)
struct.error: unpack requires a buffer of 41 bytes

**Comment by rob-blackbourn** [comment]
I've downloaded and processed the 20211231 TOPS file with no problems.

Can you check that the file has downloaded correctly? I've had problems with bad downloads before.

**Comment by DemenzEchtbaer** [comment]
> I've downloaded and processed the 20211231 TOPS file with no problems.
> 
> Can you check that the file has downloaded correctly? I've had problems with bad downloads before.

Sure thing! I'm temporarily located in a zone with poor network coverage (chances are large downloads will be corrupted), but I will try again when I go back to civilisation on Sunday.

**Comment by DemenzEchtbaer** [comment]
> I've downloaded and processed the 20211231 TOPS file with no problems.
> 
> Can you check that the file has downloaded correctly? I've had problems with bad downloads before.

Hi Rob, it seems you were right: I re-downloaded it, and it is currently parsing without any problem. I will know for sure when it reaches the end in a few moments.

Update: all good! Closing the issue, I will re-open another if something shows up. Thanks again for bringing us this package!
